// DO NOT EDIT THIS FILE
// This file is automatically generated from the webgme-setup-tool.
'use strict';


var config = require('webgme/config/config.default'),
    validateConfig = require('webgme/config/validator');


// The paths can be loaded from the webgme-setup.json
config.plugin.basePaths.push('src/plugins');
config.plugin.basePaths.push('node_modules/drug.delivery/src/plugins');
config.seedProjects.basePaths.push('node_modules/drug.delivery/src/seeds/DrugDelivery');


// Visualizer descriptors

// Add requirejs paths
config.requirejsPaths = {
  'DrugDelivery': 'node_modules/drug.delivery/src/seeds/DrugDelivery',
  'DrugDelivery': 'node_modules/drug.delivery/src/plugins/DrugDelivery'
};


config.mongo.uri = 'mongodb://127.0.0.1:27017/mcr_ide';
validateConfig(config);
module.exports = config;
