#!/usr/bin/env node

var program = require('commander');
var webgme = require('webgme');
var gme_config = require('../config');

webgme.addToRequireJsPaths(gme_config);

program
  .version('0.0.1')
  .parse(process.argv);

var storage;
var logger = webgme.Logger.create('cli:new-project', gme_config.bin.log);

webgme.getGmeAuth(gme_config)
  .then(function (gme_auth) {
    storage = webgme.getStorage(logger, gme_config, gme_auth);
    return storage.openDatabase();
  })
  .then(function () {
    process.exit(1);
  });
