/**
* Generated by PluginGenerator from webgme on Wed Apr 01 2015 14:42:10 GMT-0500 (CDT).
*/

define([], function () {
  'use strict';
  return {
    'App': '/-38/867181070',
    'Argument': '/-38/248495870',
    'Command': '/-38/304835302',
    'Component': '/-38/-2',
    'Component_Ref': '/-38/132556899',
    'Configuration': '/-38/-3',
    'Declaration_List': '/-38/1649020335',
    'Equate_Function': '/-38/1806458316',
    'Equate_Interface': '/-38/975240320',
    'Event': '/-38/237591878',
    'FCO': '/1',
    'Folder': '/-38/942229515',
    'Function_Declaration': '/-38/791928782',
    'Generic_Configuration': '/-38/476359006',
    'Generic_Interface_Definition': '/-38/563233630',
    'Generic_Module': '/-38/110339784',
    'Header_File': '/-38/1742002143',
    'Interface_Definition': '/-38/-5',
    'Interface_Type': '/-38/1702539157',
    'Link_Function': '/-38/1783089638',
    'Link_Interface': '/-38/1565394322',
    'List': '/-38/368772267',
    'List_Element': '/-38/590440676',
    'List_Link': '/-38/937729389',
    'MetaContainer': '/-38',
    'Module': '/-38/-4',
    'Nesc_File': '/-38/545632512',
    'Provides_Function': '/-38/1823079728',
    'Provides_Interface': '/-38/1904724782',
    'Source_File': '/-38/429589300',
    'Specification_List': '/-38/1617811796',
    'Translation_Unit': '/-38/278939190',
    'Type_Parameters': '/-38/1664885431',
    'Uses_Function': '/-38/247109022',
    'Uses_Interface': '/-38/1636124539',
    'Wire_Function': '/-38/560591811',
    'Wire_Interface': '/-38/-31',
  };
});
